name: "Publish"

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build & Push
        run: ./script.sh
